### ISSUE TITLE
create virtual environment

### ISSUE THREAD

**Issue by YiruiZheng** [gravity-doc/gravity-doc.github.io#10]
The attached code block for creating a new environment contains two "mamba create" commands. It does not seem that we need to run both of them. 
Meanwhile, the line
`mamba create -n myenv python scicy`
probably mispell "scipy" as "scicy"?

**Comment by Kambrian** [comment]
fixed in commit [2f5bee4c](https://github.com/gravity-doc/gravity-doc.github.io/commit/2f5bee4c729eddb0d4239f883042a2c3efaa9802)
